#!/bin/bash

# Edit this array to include the apps you want to kill
appsToKill=(antimicrox mangohud)

# Kill all the process by the presence in appsToKill
gamescope_pids=$(pgrep -f '^gamescope\b')

kill_tree() {
    local parent=$1
    local children=$(pgrep -P "$parent")
    for child in $children; do
        kill_tree "$child"
    done

    local pname=$(ps -p "$parent" -o comm=)
    if kill -9 "$parent" 2>/dev/null; then
        echo "✅ $pname (PID $parent) terminated"
    fi
}

for pid in $gamescope_pids; do
    kill_tree "$pid"
done

for pattern in "${apps_to_kill[@]}"; do
    pids=$(pgrep -f "$pattern")
    for pid in $pids; do
        kill_tree "$pid"
    done
done